### ISSUE TITLE
[ documentation ] Comparision with rsClock

### ISSUE THREAD

**Issue by yonas** [nate-sys/tuime#10]
How does this compare to `[rsClock](https://github.com/valebes/rsClock)`?

**Comment by a-usr** [comment]
Come on man. Its a clock. It shows time. Optionally with different fonts and colors. Are you concerned about features? Then compare them yourself. Are you concerned about performance? If so, why???

**Comment by yonas** [comment]
It's a clock also written in Rust. Duplication of effort. Bug fixes, new features, issue queues, etc, could be consolidated.

Now go back to bed and let real programmers talk.

**Comment by a-usr** [comment]
> It's a clock also written in Rust. 

Wow, big deal

> Duplication of effort. 

According to this ideology the linux kernel shouldnt exist since windows was already a thing when Linus Thorvalds released the first version.

> Bug fixes, new features, issue queues, etc, could be consolidated.

Yes, they *could*, but that doesnt mean that they *should*, and apart from that who are you to tell a stranger how they should handle their hobby project? 

Besides, considering the fact that apart from my MR there hasn't been any activity in a year, I'd say that nate either considers his project feature-complete, or is busy with other things, so I dont expect any new activity any time soon, and neither should you.

> Now go back to bed and let real programmers talk.

How I see it its you who should get back to bed considering your current attitude.

**Comment by nthnd** [comment]
I agree with @a-usr here. It's just a clock. Nothing remarkable.

**Comment by mazunki** [comment]
If this clock doesn't support time dilation it's literally not even future proof. Please make better software. shaking (s) my (m) head (h)

**Comment by a-usr** [comment]
> If this clock doesn't support time dilation it's literally not even future proof. Please make better software. shaking (s) my (m) head (h)

I'm having trouble trying to tell wether this is sarcasm, but just in case: Who cares wether its future proof? It doesnt have to be, does it?

**Comment by mazunki** [comment]
Isn't a clock all about time management, knowing all things past, present and future?
